//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemstones_BCSF19E034
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_stone_sizes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_stone_sizes()
        {
            this.tbl_products_stone = new HashSet<tbl_products_stone>();
        }
    
        public int size_id { get; set; }
        public string size_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_products_stone> tbl_products_stone { get; set; }
    }
}
