//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemstones_BCSF19E034
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_add_to_cart_temp
    {
        public int temp_id { get; set; }
        public string user_unique_key { get; set; }
        public Nullable<long> product_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual tbl_products_stone tbl_products_stone { get; set; }
    }
}
