//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemstones_BCSF19E034
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products_stone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_products_stone()
        {
            this.tbl_add_to_cart_temp = new HashSet<tbl_add_to_cart_temp>();
        }
    
        public long stone_id { get; set; }
        public string stone_name { get; set; }
        public decimal stone_price { get; set; }
        public string stone_description { get; set; }
        public string stone_image_url { get; set; }
        public Nullable<int> stone_category_id { get; set; }
        public Nullable<int> stone_color_id { get; set; }
        public Nullable<double> stone_weight { get; set; }
        public Nullable<int> stone_shape_id { get; set; }
        public string stone_origin { get; set; }
        public Nullable<int> stone_size_id { get; set; }
        public Nullable<double> stone_hardness { get; set; }
        public Nullable<double> stone_dispersion { get; set; }
        public Nullable<double> stone_specific_gravity { get; set; }
        public Nullable<double> stone_density { get; set; }
        public Nullable<int> stone_quantity { get; set; }
    
        public virtual tbl_stone_categories tbl_stone_categories { get; set; }
        public virtual tbl_stone_colors tbl_stone_colors { get; set; }
        public virtual tbl_stone_shapes tbl_stone_shapes { get; set; }
        public virtual tbl_stone_sizes tbl_stone_sizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_add_to_cart_temp> tbl_add_to_cart_temp { get; set; }
    }
}
