//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemstones_BCSF19E034
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orders_details
    {
        public long order_details_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public decimal product_price { get; set; }
        public Nullable<long> customer_id { get; set; }
    
        public virtual tbl_orders_main tbl_orders_main { get; set; }
        public virtual tbl_products_stone tbl_products_stone { get; set; }
    }
}
