//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemstones_BCSF19E034
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orders_main
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_orders_main()
        {
            this.tbl_orders_details = new HashSet<tbl_orders_details>();
        }
    
        public long customer_id { get; set; }
        public string customer_first_name { get; set; }
        public string customer_last_name { get; set; }
        public string customer_billing_address { get; set; }
        public string customer_email { get; set; }
        public string customer_phone { get; set; }
        public string customer_additional_info { get; set; }
        public System.DateTime created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_orders_details> tbl_orders_details { get; set; }
    }
}
